version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-docker
    ports:
      - 27017:27017

    environment:
      - MONGO_INITDB_ROOT_USERNAME=alurachallange
      - MONGO_INITDB_ROOT_PASSWORD=135790
      - MONGO_INITDB_DATABASE=alura-challange-db

    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro